# Generated by Django 5.0.1 on 2024-01-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='номер телефона клиента')),
                ('mobile_code', models.CharField(max_length=3, verbose_name='код мобильного оператора')),
                ('tag', models.CharField(max_length=100, verbose_name='тег')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_start_mailing', models.DateTimeField(verbose_name='дата и время запуска рассылки')),
                ('text_message', models.TextField(max_length=255, verbose_name='текст сообщения')),
                ('mobile_code', models.CharField(max_length=100, verbose_name='код мобильного оператора')),
                ('tag', models.CharField(max_length=100, verbose_name='тег')),
                ('date_time_stop_mailing', models.DateTimeField(verbose_name='дата и время окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_send', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailing')),
            ],
        ),
    ]
