# Generated by Django 3.2.3 on 2024-02-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mobile_code',
            field=models.CharField(max_length=3, verbose_name='код мобильного оператора'),
        ),
    ]
